spring:
  profiles:
    active: local

server:
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: true

social:
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY:"USE_YOUR_KAKAO_REST_API_KEY"}
    rest-api-secret: ${KAKAO_REST_API_SECRET:"USE_YOUR_KAKAO_REST_API_SECRET"}

jwt:
  secret-key: ${JWT_SECRET_KEY:"USE_YOUR_JWT_SECRET_KEY"}
  issuer: com.hyu-oms
  access-token:
    lifetime: ${JWT_ACCESS_TOKEN_DURATION:3600}
  refresh-token:
    lifetime: ${JWT_REFRESH_TOKEN_DURATION:259200}
